// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow to improve property demand descriptions using AI.
 *
 * - improvePropertyDemandDescription - A function that takes a property demand description and improves it using AI.
 * - ImprovePropertyDemandDescriptionInput - The input type for the improvePropertyDemandDescription function.
 * - ImprovePropertyDemandDescriptionOutput - The return type for the improvePropertyDemandDescription function.
 */

import {ai} from '@/ai/genkit';
import { googleAI } from '@genkit-ai/googleai';
import {z} from 'genkit';

const ImprovePropertyDemandDescriptionInputSchema = z.object({
  description: z.string().optional().describe('The original property demand description.'),
  propertyType: z.string().describe('The type of property (e.g., industrial, commercial).'),
  location: z.string().describe('The desired location of the property.'),
  size: z.string().describe('The desired size of the property (e.g., in square feet).'),
  readiness: z.string().optional().describe('The desired timeline for property readiness.'),
  additionalDetails: z.string().optional().describe('Any additional details about the property demand.'),
});
export type ImprovePropertyDemandDescriptionInput = z.infer<typeof ImprovePropertyDemandDescriptionInputSchema>;

const ImprovePropertyDemandDescriptionOutputSchema = z.object({
  improvedDescription: z.string().describe('The improved property demand description.'),
});
export type ImprovePropertyDemandDescriptionOutput = z.infer<typeof ImprovePropertyDemandDescriptionOutputSchema>;

export async function improvePropertyDemandDescription(input: ImprovePropertyDemandDescriptionInput): Promise<ImprovePropertyDemandDescriptionOutput> {
  return improvePropertyDemandDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improvePropertyDemandDescriptionPrompt',
  input: {schema: ImprovePropertyDemandDescriptionInputSchema},
  output: {schema: ImprovePropertyDemandDescriptionOutputSchema},
  model: googleAI.model('gemini-1.5-flash-latest'),
  prompt: `You are an expert real estate agent specializing in crafting compelling property demand descriptions.

  {{#if description}}
  Improve the following property demand description to attract more potential matches. Focus on making the description more engaging, detailed, and professional, while accurately reflecting the provided information.

  Original Description: {{{description}}}
  {{else}}
  Create a compelling property demand description based on the following details. Make it engaging, detailed, and professional.
  {{/if}}
  
  Property Type: {{{propertyType}}}
  Location: {{{location}}}
  Size: {{{size}}}
  Readiness: {{{readiness}}}
  Additional Details: {{{additionalDetails}}}

  Improved Description:`,
});

const improvePropertyDemandDescriptionFlow = ai.defineFlow(
  {
    name: 'improvePropertyDemandDescriptionFlow',
    inputSchema: ImprovePropertyDemandDescriptionInputSchema,
    outputSchema: ImprovePropertyDemandDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
