// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow to improve property demand descriptions using AI.
 *
 * - improvePropertyDemandDescription - A function that takes a property demand description and improves it using AI.
 * - ImprovePropertyDemandDescriptionInput - The input type for the improvePropertyDemandDescription function.
 * - ImprovePropertyDemandDescriptionOutput - The return type for the improvePropertyDemandDescription function.
 */

import {ai} from '@/ai/genkit';
import { googleAI } from '@genkit-ai/googleai';
import {z} from 'genkit';

const ImprovePropertyDemandDescriptionInputSchema = z.object({
  description: z.string().optional().describe('The original property demand description.'),
  propertyType: z.string().describe('The type of property (e.g., industrial, commercial).'),
  location: z.string().describe('The desired location name of the property (e.g., "Oragadam, Chennai"). NEVER use coordinates.'),
  size: z.string().describe('The desired size of the property (e.g., in square feet).'),
  readiness: z.string().optional().describe('The desired timeline for property readiness.'),
  additionalDetails: z.string().optional().describe('Any additional details about the property demand.'),
});
export type ImprovePropertyDemandDescriptionInput = z.infer<typeof ImprovePropertyDemandDescriptionInputSchema>;

const ImprovePropertyDemandDescriptionOutputSchema = z.object({
  improvedDescription: z.string().describe('The improved property demand description.'),
});
export type ImprovePropertyDemandDescriptionOutput = z.infer<typeof ImprovePropertyDemandDescriptionOutputSchema>;

export async function improvePropertyDemandDescription(input: ImprovePropertyDemandDescriptionInput): Promise<ImprovePropertyDemandDescriptionOutput> {
  return improvePropertyDemandDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improvePropertyDemandDescriptionPrompt',
  input: {schema: ImprovePropertyDemandDescriptionInputSchema},
  output: {schema: ImprovePropertyDemandDescriptionOutputSchema},
  model: googleAI.model('gemini-1.5-flash-latest'),
  prompt: `You are an expert real estate agent specializing in writing clear and professional property DEMAND requests on behalf of a client. Your tone should be that of a company seeking a property, not advertising one. You MUST use the provided location name and NEVER use coordinates.

  {{#if description}}
  Based on the original description and the structured details below, write an improved and comprehensive demand description from the perspective of a company looking for a property.

  Original Description: {{{description}}}
  {{else}}
  Based on the following details, write a comprehensive and professional demand description from the perspective of a company looking for a property.
  {{/if}}
  
  **Client Requirement Details:**
  - Property Type Needed: {{{propertyType}}}
  - Desired Location Name: {{{location}}}
  - Required Size: {{{size}}} Sq. Ft.
  - Occupancy Timeline: {{{readiness}}}
  - Other Specifications: {{{additionalDetails}}}

  Improved Demand Description:`,
});

const improvePropertyDemandDescriptionFlow = ai.defineFlow(
  {
    name: 'improvePropertyDemandDescriptionFlow',
    inputSchema: ImprovePropertyDemandDescriptionInputSchema,
    outputSchema: ImprovePropertyDemandDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
