export type SubmissionStatus = "Pending" | "Shortlisted" | "Rejected";

export const mockDemands = [
  {
    demandId: 'ACME-1689345',
    userEmail: 'user@example.com',
    companyName: 'ACME Corp',
    userName: 'John Doe',
    userPhone: '123-456-7890',
    propertyType: 'Warehouse',
    location: '12.9716, 77.5946',
    radius: 20,
    size: 100000,
    readiness: 'Immediate',
    ceilingHeight: 40,
    docks: 12,
    description: 'Urgent requirement for a large warehouse with high ceilings and 10+ docks near the port.',
    preferences: {
      nonCompromisable: ['size', 'docks'],
    },
  },
  {
    demandId: 'TECHCORP-1689346',
    userEmail: 'user@example.com',
    companyName: 'TechCorp',
    userName: 'Jane Smith',
    userPhone: '123-456-7890',
    propertyType: 'Industrial Building',
    location: '13.0827, 80.2707',
    radius: 10,
    size: 25000,
    readiness: 'Within 90 Days',
    ceilingHeight: 25,
    docks: 4,
    description: 'Need an industrial building for a light assembly line. Good connectivity is a must.',
    preferences: {
      nonCompromisable: ['location'],
    },
  },
  {
    demandId: 'RETAILCO-1689347',
    userEmail: 'anotheruser@example.com',
    companyName: 'RetailCo',
    userName: 'Peter Jones',
    userPhone: '123-456-7890',
    propertyType: 'Warehouse',
    location: '28.6139, 77.2090',
    radius: 15,
    size: 15000,
    readiness: 'Immediate',
    ceilingHeight: 20,
    docks: 2,
    description: 'Looking for a warehouse for e-commerce fulfillment in the city center. Must be ready for immediate occupation.',
    preferences: {
      nonCompromisable: ['location', 'readiness'],
    },
  },
    {
    demandId: 'GLOBAL-1689348',
    userEmail: 'anotheruser@example.com',
    companyName: 'Global Industries',
    userName: 'Mary Williams',
    userPhone: '123-456-7890',
    propertyType: 'Industrial Building',
    location: '13.0827, 80.2707',
    radius: 25,
    size: 250000,
    readiness: 'BTS',
    ceilingHeight: 50,
    docks: 20,
    description: 'Industrial facility for manufacturing, requiring heavy power load and effluent treatment plant.',
    preferences: {
      nonCompromisable: ['size', 'power', 'fireSafety'],
    },
  },
];


export const mockSubmissions = [
  {
    demandId: 'ACME-1689345',
    property: {
      propertyId: 'PS-ACME-001',
      propertyGeoLocation: '12.9716, 77.5946',
      size: 105000,
      floor: 'Ground',
      readinessToOccupy: 'Immediate',
      siteType: 'Part of Industrial Park',
      safety: 'Fully Compounded with 24/7 Security',
      ceilingHeight: 42,
      rentPerSft: 22,
      rentalSecurityDeposit: 6,
      userType: 'Developer',
      userName: 'Admin',
      userCompanyName: 'Origin Depot Properties',
      userPhoneNumber: 'N/A',
      userEmail: 'admin@example.com',
      o2oDealDemandId: 'ACME-1689345',
      approvalStatus: 'Obtained',
      approvalAuthority: 'BDA',
      installedCapacity: '500 kva',
      availablePower: '450 kva',
      genSetBackup: 'Available',
      fireHydrant: 'Installed',
      fireNoc: 'Obtained',
      docks: 12,
      canopy: 'Installed',
      additionalInformation: 'State-of-the-art facility with modern amenities.',
    },
    matchResult: {
      overallScore: 0.95,
      scoreBreakdown: {
        location: 1.0,
        size: 0.9,
        features: 0.95,
      },
      justification: "This property is an excellent match. It slightly exceeds the requested size and is in the perfect location, meeting all critical feature requirements like docks and ceiling height.",
    },
  },
  {
    demandId: 'ACME-1689345',
    property: {
      propertyId: 'PS-ACME-002',
      propertyGeoLocation: '12.9716, 77.5946',
      size: 90000,
      floor: 'Ground',
      readinessToOccupy: 'Immediate',
      siteType: 'Standalone',
      safety: 'Partially compounded',
      ceilingHeight: 38,
      rentPerSft: 19,
      rentalSecurityDeposit: 8,
      userType: 'Owner',
      userName: 'Some Owner',
      userCompanyName: 'Value Warehousing',
      userPhoneNumber: 'N/A',
      userEmail: 'someowner@example.com',
      o2oDealDemandId: 'ACME-1689345',
      approvalStatus: 'Obtained',
      approvalAuthority: 'BDA',
      installedCapacity: '400 kva',
      availablePower: '350 kva',
      genSetBackup: 'Can be provided',
      fireHydrant: 'Can be provided',
      fireNoc: 'Applied For',
      docks: 10,
      canopy: 'Can be provided',
      additionalInformation: 'Economical option, slightly smaller than requested.',
    },
    matchResult: {
      overallScore: 0.78,
      scoreBreakdown: {
        location: 1.0,
        size: 0.2,
        features: 0.8,
      },
      justification: "Good location match, but the size is below the 10% tolerance for your non-compromisable requirement. It also has fewer docks than requested.",
    },
  },
    {
    demandId: 'TECHCORP-1689346',
    property: {
      propertyId: 'PS-TECH-001',
      propertyGeoLocation: '13.1986, 77.7066',
      size: 25000,
      floor: 'First Floor',
      readinessToOccupy: 'Within 45 Days',
      siteType: 'Part of Commercial Project',
      safety: 'Fully Compounded',
      ceilingHeight: 28,
      rentPerSft: 35,
      rentalSecurityDeposit: 10,
      userType: 'Developer',
      userName: 'Admin',
      userCompanyName: 'Origin Depot Properties',
      userPhoneNumber: 'N/A',
      userEmail: 'admin@example.com',
      o2oDealDemandId: 'TECHCORP-1689346',
      approvalStatus: 'Obtained',
      approvalAuthority: 'CMDA',
      installedCapacity: '200 kva',
      availablePower: '200 kva',
      genSetBackup: 'Can be provided',
      fireHydrant: 'Installed',
      fireNoc: 'Obtained',
      docks: 5,
      canopy: 'Installed',
      additionalInformation: 'Grade A space suitable for light industrial work.',
    },
    matchResult: {
      overallScore: 0.18,
      scoreBreakdown: {
        location: 0.2,
        size: 1.0,
        features: 0.9,
      },
      justification: "This property matches your size and feature requirements well. However, because 'location' was marked as non-compromisable, the score is very low as the property is assumed to be outside the specified radius.",
    },
  },
];
