
import { Submission } from "@/contexts/data-context";

export const mockDemands = [
  {
    demandId: 'DMD-1700000000001',
    userEmail: 'user@example.com',
    companyName: 'ACME Corp',
    userName: 'John Doe',
    userPhone: '123-456-7890',
    propertyType: 'Warehouse',
    location: '12.9716, 77.5946',
    locationName: 'Bengaluru, Karnataka, India',
    radius: 20,
    size: 100000,
    readiness: 'Immediate',
    ceilingHeight: 40,
    docks: 12,
    description: 'Urgent requirement for a large warehouse with high ceilings and 10+ docks near the port.',
    preferences: {
      nonCompromisable: ['size', 'docks'],
    },
  },
  {
    demandId: 'DMD-1700000000002',
    userEmail: 'user@example.com',
    companyName: 'TechCorp',
    userName: 'Jane Smith',
    userPhone: '123-456-7890',
    propertyType: 'Industrial Building',
    location: '13.0827, 80.2707',
    locationName: 'Chennai, Tamil Nadu, India',
    radius: 10,
    size: 25000,
    readiness: 'Within 90 Days',
    ceilingHeight: 25,
    docks: 4,
    description: 'Need an industrial building for a light assembly line. Good connectivity is a must.',
    preferences: {
      nonCompromisable: ['location'],
    },
  },
  {
    demandId: 'DMD-1700000000003',
    userEmail: 'user@example.com',
    companyName: 'RetailCo',
    userName: 'Peter Jones',
    userPhone: '123-456-7890',
    propertyType: 'Warehouse',
    location: '28.6139, 77.2090',
    locationName: 'New Delhi, Delhi, India',
    radius: 15,
    size: 15000,
    readiness: 'Immediate',
    ceilingHeight: 20,
    docks: 2,
    description: 'Looking for a warehouse for e-commerce fulfillment in the city center. Must be ready for immediate occupation.',
    preferences: {
      nonCompromisable: ['location', 'readiness'],
    },
  },
    {
    demandId: 'DMD-1700000000004',
    userEmail: 'user@example.com',
    companyName: 'Global Industries',
    userName: 'Mary Williams',
    userPhone: '123-456-7890',
    propertyType: 'Industrial Building',
    location: '13.0827, 80.2707',
    locationName: 'Chennai, Tamil Nadu, India',
    radius: 25,
    size: 250000,
    readiness: 'BTS',
    ceilingHeight: 50,
    docks: 20,
    description: 'Industrial facility for manufacturing, requiring heavy power load and effluent treatment plant.',
    preferences: {
      nonCompromisable: ['size', 'power', 'fireSafety'],
    },
  },
  {
    demandId: 'DMD-1700000000005',
    userEmail: 'logistics.pro@example.com',
    companyName: 'ProLogistics Solutions',
    userName: 'Sunil Patel',
    userPhone: '555-987-6543',
    propertyType: 'Warehouse',
    location: '13.0827, 80.2707',
    locationName: 'Chennai Port Area',
    radius: 15,
    size: 200000,
    readiness: 'Within 90 Days',
    ceilingHeight: 45,
    docks: 15,
    description: 'Tier-1 logistics firm requires a Grade A PEB warehouse for a major e-commerce client. Facility must be compliant with all modern fire safety norms (NOC obtained), have high ceiling clearance for vertical storage, and ample docking stations for high-volume turnover. Non-compromisable on fire safety, ceiling height, and readiness.',
    preferences: {
      nonCompromisable: ['fireNoc', 'ceilingHeight', 'readiness'],
    },
  },
];


export const mockSubmissions: Submission[] = [
  {
    demandId: 'DMD-1700000000001',
    property: {
      propertyId: 'PS-ACME-001',
      propertyGeoLocation: 'Bengaluru, Karnataka, India',
      size: 105000,
      floor: 'Ground',
      readinessToOccupy: 'Immediate',
      siteType: 'Part of Industrial Park',
      safety: 'Fully Compounded with 24/7 Security',
      ceilingHeight: 42,
      rentPerSft: 22,
      rentalSecurityDeposit: 6,
      userType: 'Developer',
      userName: 'Admin',
      userCompanyName: 'Origin Depot Properties',
      userPhoneNumber: 'N/A',
      userEmail: 'admin@example.com',
      o2oDealDemandId: 'DMD-1700000000001',
      approvalStatus: 'Obtained',
      approvalAuthority: 'BDA',
      installedCapacity: '500 kva',
      availablePower: '450 kva',
      genSetBackup: 'Available',
      fireHydrant: 'Installed',
      fireNoc: 'Obtained',
      docks: 12,
      canopy: 'Installed',
      additionalInformation: 'State-of-the-art facility with modern amenities.',
    },
    matchResult: {
      overallScore: 0.95,
      scoreBreakdown: {
        location: 1.0,
        size: 0.9,
        features: 0.95,
      },
      justification: "This property is an excellent match. It slightly exceeds the requested size and is in the perfect location, meeting all critical feature requirements like docks and ceiling height.",
    },
    status: 'Approved',
  },
  {
    demandId: 'DMD-1700000000001',
    property: {
      propertyId: 'PS-ACME-002',
      propertyGeoLocation: 'Bengaluru, Karnataka, India',
      size: 90000,
      floor: 'Ground',
      readinessToOccupy: 'Immediate',
      siteType: 'Standalone',
      safety: 'Partially compounded',
      ceilingHeight: 38,
      rentPerSft: 19,
      rentalSecurityDeposit: 8,
      userType: 'Owner',
      userName: 'Some Owner',
      userCompanyName: 'Value Warehousing',
      userPhoneNumber: 'N/A',
      userEmail: 'someowner@example.com',
      o2oDealDemandId: 'DMD-1700000000001',
      approvalStatus: 'Obtained',
      approvalAuthority: 'BDA',
      installedCapacity: '400 kva',
      availablePower: '350 kva',
      genSetBackup: 'Can be provided',
      fireHydrant: 'Can be provided',
      fireNoc: 'Applied For',
      docks: 10,
      canopy: 'Can be provided',
      additionalInformation: 'Economical option, slightly smaller than requested.',
    },
    matchResult: {
      overallScore: 0.78,
      scoreBreakdown: {
        location: 1.0,
        size: 0.2,
        features: 0.8,
      },
      justification: "Good location match, but the size is below the 10% tolerance for your non-compromisable requirement. It also has fewer docks than requested.",
    },
    status: 'Pending',
  },
    {
    demandId: 'DMD-1700000000002',
    property: {
      propertyId: 'PS-TECH-001',
      propertyGeoLocation: 'Chennai, Tamil Nadu, India',
      size: 25000,
      floor: 'First Floor',
      readinessToOccupy: 'Within 45 Days',
      siteType: 'Part of Commercial Project',
      safety: 'Fully Compounded',
      ceilingHeight: 28,
      rentPerSft: 35,
      rentalSecurityDeposit: 10,
      userType: 'Developer',
      userName: 'Admin',
      userCompanyName: 'Origin Depot Properties',
      userPhoneNumber: 'N/A',
      userEmail: 'admin@example.com',
      o2oDealDemandId: 'DMD-1700000000002',
      approvalStatus: 'Obtained',
      approvalAuthority: 'CMDA',
      installedCapacity: '200 kva',
      availablePower: '200 kva',
      genSetBackup: 'Can be provided',
      fireHydrant: 'Installed',
      fireNoc: 'Obtained',
      docks: 5,
      canopy: 'Installed',
      additionalInformation: 'Grade A space suitable for light industrial work.',
    },
    matchResult: {
      overallScore: 0.18,
      scoreBreakdown: {
        location: 0.2,
        size: 1.0,
        features: 0.9,
      },
      justification: "This property matches your size and feature requirements well. However, because 'location' was marked as non-compromisable, the score is very low as the property is assumed to be outside the specified radius.",
    },
    status: 'Rejected',
  },
  {
    demandId: 'DMD-1700000000005',
    property: {
      propertyId: 'PS-LOGI-001',
      propertyGeoLocation: 'Chennai Port Area',
      size: 210000,
      floor: 'Ground',
      readinessToOccupy: 'Within 45 Days',
      siteType: 'Part of Industrial Park',
      safety: 'Fully Compounded, Fire safety compliant',
      ceilingHeight: 48,
      rentPerSft: 25,
      rentalSecurityDeposit: 10,
      userType: 'Developer',
      userName: 'Admin',
      userCompanyName: 'Origin Depot Properties',
      userPhoneNumber: 'N/A',
      userEmail: 'admin@example.com',
      o2oDealDemandId: 'DMD-1700000000005',
      approvalStatus: 'Obtained',
      approvalAuthority: 'CMDA',
      installedCapacity: '1 mva',
      availablePower: '1 mva',
      genSetBackup: 'Available',
      fireHydrant: 'Installed',
      fireNoc: 'Obtained',
      docks: 16,
      canopy: 'Installed',
      additionalInformation: 'Brand new Grade-A+ facility with ESFR sprinklers and 8-ton point load flooring.',
    },
    matchResult: {
      overallScore: 0.92,
      scoreBreakdown: {
        location: 0.9,
        size: 0.9,
        features: 0.95,
      },
      justification: "Excellent match. This property meets all non-compromisable requirements for readiness, ceiling height, and fire NOC. It also offers more docks than required and is a good size fit.",
    },
    status: 'Approved',
  },
  {
    demandId: 'DMD-1700000000005',
    property: {
      propertyId: 'PS-LOGI-002',
      propertyGeoLocation: 'Near Chennai Port',
      size: 200000,
      floor: 'Ground',
      readinessToOccupy: 'Immediate',
      siteType: 'Standalone',
      safety: 'Fully Compounded',
      ceilingHeight: 35,
      rentPerSft: 21,
      rentalSecurityDeposit: 10,
      userType: 'Owner',
      userName: 'Some Owner',
      userCompanyName: 'Value Warehousing',
      userPhoneNumber: 'N/A',
      userEmail: 'someowner@example.com',
      o2oDealDemandId: 'DMD-1700000000005',
      approvalStatus: 'Obtained',
      approvalAuthority: 'CMDA',
      installedCapacity: '800 kva',
      availablePower: '750 kva',
      genSetBackup: 'Available',
      fireHydrant: 'Installed',
      fireNoc: 'Obtained',
      docks: 15,
      canopy: 'Installed',
      additionalInformation: 'Older facility, available immediately.',
    },
    matchResult: {
      overallScore: 0.15,
      scoreBreakdown: {
        location: 0.9,
        size: 1.0,
        features: 0.2,
      },
      justification: "This property is a poor match. Although it meets the readiness and fire NOC requirements, the ceiling height of 35 ft is significantly lower than the 45 ft specified as a non-compromisable item, making it unsuitable for the client's vertical storage needs.",
    },
    status: 'Pending',
  },
];
