
import { Submission } from "@/contexts/data-context";
import { DemandSchema } from "./schema";

export const mockDemands: DemandSchema[] = [
  {
    demandId: 'DMD-1700000000001',
    userEmail: 'user@example.com',
    companyName: 'ACME Corp',
    userName: 'John Doe',
    userPhone: '123-456-7890',
    propertyType: 'Warehouse',
    location: '12.9716, 77.5946',
    locationName: 'Bengaluru, Karnataka, India',
    radius: 20,
    size: 100000,
    readiness: 'Immediate',
    ceilingHeight: 40,
    docks: 12,
    description: 'Urgent requirement for a large warehouse with high ceilings and 10+ docks near the port.',
    preferences: {
      nonCompromisable: ['size', 'docks'],
    },
  },
  {
    demandId: 'DMD-1700000000002',
    userEmail: 'user@example.com',
    companyName: 'TechCorp',
    userName: 'Jane Smith',
    userPhone: '123-456-7890',
    propertyType: 'Industrial Building',
    location: '13.0827, 80.2707',
    locationName: 'Chennai, Tamil Nadu, India',
    radius: 10,
    size: 25000,
    readiness: 'Within 90 Days',
    ceilingHeight: 25,
    docks: 4,
    description: 'Need an industrial building for a light assembly line. Good connectivity is a must.',
    preferences: {
      nonCompromisable: ['location'],
    },
  },
  {
    demandId: 'DMD-1700000000003',
    userEmail: 'user@example.com',
    companyName: 'RetailCo',
    userName: 'Peter Jones',
    userPhone: '123-456-7890',
    propertyType: 'Warehouse',
    location: '28.6139, 77.2090',
    locationName: 'New Delhi, Delhi, India',
    radius: 15,
    size: 15000,
    readiness: 'Immediate',
    ceilingHeight: 20,
    docks: 2,
    description: 'Looking for a warehouse for e-commerce fulfillment in the city center. Must be ready for immediate occupation.',
    preferences: {
      nonCompromisable: ['location', 'readiness'],
    },
  },
  {
    demandId: 'DMD-1700000000004',
    userEmail: 'user@example.com',
    companyName: 'Global Industries',
    userName: 'Mary Williams',
    userPhone: '123-456-7890',
    propertyType: 'Industrial Building',
    location: '13.0827, 80.2707',
    locationName: 'Chennai, Tamil Nadu, India',
    radius: 25,
    size: 250000,
    readiness: 'BTS',
    ceilingHeight: 50,
    docks: 20,
    description: 'Industrial facility for manufacturing, requiring heavy power load and effluent treatment plant.',
    preferences: {
      nonCompromisable: ['size', 'power', 'fireSafety'],
    },
  },
  {
    demandId: 'DMD-1700000000005',
    userEmail: 'logistics.pro@example.com',
    companyName: 'ProLogistics Solutions',
    userName: 'Sunil Patel',
    userPhone: '555-987-6543',
    propertyType: 'Warehouse',
    location: '13.0827, 80.2707',
    locationName: 'Chennai Port Area',
    radius: 15,
    size: 200000,
    readiness: 'Within 90 Days',
    ceilingHeight: 45,
    docks: 15,
    description: 'Tier-1 logistics firm requires a Grade A PEB warehouse. Facility must be compliant with all modern fire safety norms (NOC obtained), have high ceiling clearance for vertical storage, and ample docking stations for high-volume turnover. Non-compromisable on fire safety, ceiling height, and readiness.',
    preferences: {
      nonCompromisable: ['fireNoc', 'ceilingHeight', 'readiness'],
    },
  },
  {
      demandId: 'DMD-1710000000006',
      userEmail: 'user@example.com',
      companyName: 'PharmaSafe Inc.',
      userName: 'Dr. Evelyn Reed',
      userPhone: '555-333-4444',
      propertyType: 'Warehouse',
      location: '19.0760, 72.8777',
      locationName: 'Mumbai, Maharashtra',
      radius: 10,
      size: 50000,
      readiness: 'Immediate',
      ceilingHeight: 30,
      docks: 6,
      description: 'Need a temperature-controlled warehouse for pharmaceutical storage. Must have all statutory approvals (CMDA/BDA) and an obtained Fire NOC. Consistent power with full generator backup is non-negotiable due to the sensitive nature of the products. The lease must be budget-friendly.',
      preferences: {
          nonCompromisable: ['approvals', 'fireNoc', 'power'],
      },
  },
  {
      demandId: 'DMD-1720000000007',
      userEmail: 'user@example.com',
      companyName: 'AutoParts Express',
      userName: 'Rajesh Singh',
      userPhone: '555-555-6666',
      propertyType: 'Industrial Building',
      location: '12.83, 79.95',
      locationName: 'Oragadam Industrial Corridor',
      radius: 5,
      size: 120000,
      readiness: 'Within 45 Days',
      ceilingHeight: 45,
      docks: 18,
      description: 'Automotive components supplier looking for a high-throughput facility. A minimum of 45 ft ceiling height is required for our automated racking systems. The number of docks is critical for our logistics. The property must be part of an industrial park with excellent road access. Fire safety compliance is a must.',
      preferences: {
          nonCompromisable: ['ceilingHeight', 'docks', 'fireSafety'],
      },
  },
  {
      demandId: 'DMD-1730000000008',
      userEmail: 'user@example.com',
      companyName: 'FrostyFoods Logistics',
      userName: 'Mei Lin',
      userPhone: '555-777-8888',
      propertyType: 'Warehouse',
      location: '22.5726, 88.3639',
      locationName: 'Kolkata, West Bengal',
      radius: 20,
      size: 75000,
      readiness: 'BTS',
      ceilingHeight: 35,
      docks: 10,
      description: 'Cold storage solutions provider looking for a Build-To-Suit (BTS) opportunity. We require a standalone facility with space for our refrigeration units. A high installed power capacity is essential. All approvals for a cold storage facility must be obtainable (To Apply).',
      preferences: {
          nonCompromisable: ['readiness', 'power', 'approvals'],
      },
  },
];


export const mockSubmissions: Submission[] = [
  {
    demandId: 'DMD-1700000000001',
    property: {
      propertyId: 'PS-ACME-001',
      propertyGeoLocation: 'Bengaluru, Karnataka, India',
      isLocationConfirmed: true,
      size: 105000,
      floor: 'Ground',
      readinessToOccupy: 'Immediate',
      siteType: 'Part of Industrial Park',
      safety: 'Fully Compounded with 24/7 Security',
      ceilingHeight: 42,
      rentPerSft: 22,
      rentalSecurityDeposit: 6,
      userType: 'Developer',
      userName: 'Admin',
      userCompanyName: 'Origin Depot Properties',
      userPhoneNumber: 'N/A',
      userEmail: 'admin@example.com',
      o2oDealDemandId: 'DMD-1700000000001',
      approvalStatus: 'Obtained',
      approvalAuthority: 'BDA',
      installedCapacity: '500 kva',
      availablePower: '450 kva',
      genSetBackup: 'Available',
      fireHydrant: 'Installed',
      fireNoc: 'Obtained',
      docks: 12,
      canopy: 'Installed',
      additionalInformation: 'State-of-the-art facility with modern amenities.',
    },
    matchResult: {
      overallScore: 0.98,
      scoreBreakdown: {
        location: 1.0,
        size: 0.95,
        commercials: 0.9,
        power: 0.9,
        fireSafety: 1.0,
        approvals: 1.0,
        amenities: 1.0,
      },
      justification: "This property is an excellent match. It slightly exceeds the requested size and is in the perfect location, meeting all critical feature requirements like docks and ceiling height.",
    },
    status: 'Approved',
    isNew: true,
    demandUserEmail: 'user@example.com',
  },
  {
    demandId: 'DMD-1700000000001',
    property: {
      propertyId: 'PS-ACME-002',
      propertyGeoLocation: 'Bengaluru, Karnataka, India',
      isLocationConfirmed: true,
      size: 92000,
      floor: 'Ground',
      readinessToOccupy: 'Immediate',
      siteType: 'Standalone',
      safety: 'Partially compounded',
      ceilingHeight: 38,
      rentPerSft: 19,
      rentalSecurityDeposit: 8,
      userType: 'Owner',
      userName: 'Some Owner',
      userCompanyName: 'Value Warehousing',
      userPhoneNumber: 'N/A',
      userEmail: 'someowner@example.com',
      o2oDealDemandId: 'DMD-1700000000001',
      approvalStatus: 'Obtained',
      approvalAuthority: 'BDA',
      installedCapacity: '400 kva',
      availablePower: '350 kva',
      genSetBackup: 'Can be provided',
      fireHydrant: 'Can be provided',
      fireNoc: 'Applied For',
      docks: 11,
      canopy: 'Can be provided',
      additionalInformation: 'Economical option, slightly smaller than requested.',
    },
    matchResult: {
      overallScore: 0.10,
      scoreBreakdown: {
        location: 1.0,
        size: 0.1,
        commercials: 0.9,
        power: 0.9,
        fireSafety: 0.6,
        approvals: 1.0,
        amenities: 0.1,
      },
      justification: "Location Score: 1.0 - Location confirmed by the provider. Size Score: 0.1 - The property size (92,000 sq ft) is significantly smaller than the demand (100,000 sq ft) which is a non-compromisable item. Amenities Score: 0.1 - The property has 11 docks out of the required 12, which is a non-compromisable item. The ceiling height of 38ft is also lower than the required 40ft.",
    },
    status: 'Pending',
    isNew: false,
    demandUserEmail: 'user@example.com',
  },
    {
    demandId: 'DMD-1700000000002',
    property: {
      propertyId: 'PS-TECH-001',
      isLocationConfirmed: false,
      propertyGeoLocation: 'Chennai, Tamil Nadu, India',
      size: 25000,
      floor: 'First Floor',
      readinessToOccupy: 'Within 45 Days',
      siteType: 'Part of Commercial Project',
      safety: 'Fully Compounded',
      ceilingHeight: 28,
      rentPerSft: 35,
      rentalSecurityDeposit: 10,
      userType: 'Developer',
      userName: 'Admin',
      userCompanyName: 'Origin Depot Properties',
      userPhoneNumber: 'N/A',
      userEmail: 'admin@example.com',
      o2oDealDemandId: 'DMD-1700000000002',
      approvalStatus: 'Obtained',
      approvalAuthority: 'CMDA',
      installedCapacity: '200 kva',
      availablePower: '200 kva',
      genSetBackup: 'Can be provided',
      fireHydrant: 'Installed',
      fireNoc: 'Obtained',
      docks: 5,
      canopy: 'Installed',
      additionalInformation: 'Grade A space suitable for light industrial work.',
    },
    matchResult: {
      overallScore: 0.61,
      scoreBreakdown: {
        location: 0.1,
        size: 1.0,
        commercials: 0.9,
        power: 0.9,
        fireSafety: 1.0,
        approvals: 1.0,
        amenities: 0.9,
      },
      justification: "This property matches your size and feature requirements well. However, because 'location' was marked as non-compromisable, the score is very low as the property's location is unverified. This significantly impacts the overall score.",
    },
    status: 'Rejected',
    isNew: false,
    demandUserEmail: 'user@example.com',
  },
  {
    demandId: 'DMD-1700000000005',
    property: {
      propertyId: 'PS-LOGI-001',
      isLocationConfirmed: true,
      propertyGeoLocation: 'Chennai Port Area',
      size: 210000,
      floor: 'Ground',
      readinessToOccupy: 'Within 45 Days',
      siteType: 'Part of Industrial Park',
      safety: 'Fully Compounded, Fire safety compliant',
      ceilingHeight: 48,
      rentPerSft: 25,
      rentalSecurityDeposit: 10,
      userType: 'Developer',
      userName: 'Admin',
      userCompanyName: 'Origin Depot Properties',
      userPhoneNumber: 'N/A',
      userEmail: 'admin@example.com',
      o2oDealDemandId: 'DMD-1700000000005',
      approvalStatus: 'Obtained',
      approvalAuthority: 'CMDA',
      installedCapacity: '1 mva',
      availablePower: '1 mva',
      genSetBackup: 'Available',
      fireHydrant: 'Installed',
      fireNoc: 'Obtained',
      docks: 16,
      canopy: 'Installed',
      additionalInformation: 'Brand new Grade-A+ facility with ESFR sprinklers and 8-ton point load flooring.',
    },
    matchResult: {
      overallScore: 0.98,
      scoreBreakdown: {
        location: 1.0,
        size: 0.95,
        commercials: 0.9,
        power: 0.9,
        fireSafety: 1.0,
        approvals: 1.0,
        amenities: 1.0,
      },
      justification: "Excellent match. This property meets all non-compromisable requirements for readiness, ceiling height, and fire NOC. It also offers more docks than required and is a good size fit.",
    },
    status: 'Approved',
    isNew: true,
    demandUserEmail: 'logistics.pro@example.com',
  },
  {
    demandId: 'DMD-1700000000005',
    property: {
      propertyId: 'PS-LOGI-002',
      isLocationConfirmed: true,
      propertyGeoLocation: 'Near Chennai Port',
      size: 200000,
      floor: 'Ground',
      readinessToOccupy: 'Immediate',
      siteType: 'Standalone',
      safety: 'Fully Compounded',
      ceilingHeight: 35,
      rentPerSft: 21,
      rentalSecurityDeposit: 10,
      userType: 'Owner',
      userName: 'Some Owner',
      userCompanyName: 'Value Warehousing',
      userPhoneNumber: 'N/A',
      userEmail: 'someowner@example.com',
      o2oDealDemandId: 'DMD-1700000000005',
      approvalStatus: 'Obtained',
      approvalAuthority: 'CMDA',
      installedCapacity: '800 kva',
      availablePower: '750 kva',
      genSetBackup: 'Available',
      fireHydrant: 'Installed',
      fireNoc: 'Obtained',
      docks: 15,
      canopy: 'Installed',
      additionalInformation: 'Older facility, available immediately.',
    },
    matchResult: {
      overallScore: 0.77,
      scoreBreakdown: {
        location: 1.0,
        size: 1.0,
        commercials: 0.9,
        power: 0.9,
        fireSafety: 1.0,
        approvals: 1.0,
        amenities: 0.78,
      },
      justification: "This property is a poor match. Although it meets the readiness and fire NOC requirements, the ceiling height of 35 ft is significantly lower than the 45 ft specified as a non-compromisable item, making it unsuitable for the client's vertical storage needs. This brings the amenities score down significantly.",
    },
    status: 'Pending',
    isNew: false,
    demandUserEmail: 'logistics.pro@example.com',
  },
];
