
import { type WarehouseSchema } from "./schema";

// This is a helper function to satisfy the transformed schema structure
const createWarehouseEntry = (entry: Omit<WarehouseSchema, 'latLng' | 'generalizedLocation'> & {
    lat: number;
    lng: number;
}): WarehouseSchema => {
    return {
        ...entry,
        latLng: `${entry.lat}, ${entry.lng}`,
        generalizedLocation: {
            lat: entry.lat,
            lng: entry.lng,
        }
    };
};


export const warehouses: WarehouseSchema[] = [
  createWarehouseEntry({
    id: 'WH-001',
    locationName: 'Oragadam',
    isActive: true,
    lat: 12.83,
    lng: 79.95,
    size: 150000,
    readiness: 'Ready for Occupancy',
    specifications: {
        ceilingHeight: 45,
        docks: 20,
        officeSpace: true,
        flooringType: 'FM2 Grade',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  }),
  createWarehouseEntry({
    id: 'WH-002',
    locationName: 'Sriperumbudur',
    isActive: true,
    lat: 12.96,
    lng: 79.95,
    size: 250000,
    readiness: 'Under Construction',
    specifications: {
        ceilingHeight: 50,
        docks: 30,
        officeSpace: true,
        flooringType: 'Heavy Duty',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  }),
  createWarehouseEntry({
    id: 'WH-003',
    locationName: 'Guindy',
    isActive: false, // This one is inactive
    lat: 13.0102,
    lng: 80.2156,
    size: 50000,
    readiness: 'Ready for Occupancy',
    specifications: {
        ceilingHeight: 25,
        docks: 5,
        officeSpace: true,
        flooringType: 'Standard',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
    ],
  }),
  createWarehouseEntry({
    id: 'WH-004',
    locationName: 'Bhiwandi',
    isActive: true,
    lat: 19.30,
    lng: 73.06,
    size: 500000,
    readiness: 'Ready for Occupancy',
    specifications: {
        ceilingHeight: 40,
        docks: 50,
        officeSpace: true,
        flooringType: 'FM2 Grade',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  }),
  createWarehouseEntry({
    id: 'WH-005',
    locationName: 'Hosur',
    isActive: true,
    lat: 12.75,
    lng: 77.82,
    size: 120000,
    readiness: 'Available in 3 months',
    specifications: {
        ceilingHeight: 40,
        docks: 15,
        officeSpace: false,
        flooringType: 'Standard',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  }),
  createWarehouseEntry({
    id: 'WH-006',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.13,
    lng: 79.91,
    size: 80000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 35, docks: 8, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-007',
    locationName: 'Vallam-Vadagal',
    isActive: true,
    lat: 12.92,
    lng: 79.93,
    size: 300000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 50, docks: 35, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-008',
    locationName: 'Mannur',
    isActive: true,
    lat: 13.04,
    lng: 79.99,
    size: 125000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 12, officeSpace: false, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-009',
    locationName: 'Mappedu',
    isActive: true,
    lat: 13.09,
    lng: 79.95,
    size: 95000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 30, docks: 10, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-010',
    locationName: 'Sunguvarchatram',
    isActive: true,
    lat: 12.97,
    lng: 79.84,
    size: 450000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 55, docks: 40, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-011',
    locationName: 'Walajabad',
    isActive: true,
    lat: 12.80,
    lng: 79.83,
    size: 75000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 6, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-012',
    locationName: 'Redhills',
    isActive: true,
    lat: 13.17,
    lng: 80.20,
    size: 220000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 40, docks: 25, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-013',
    isActive: true,
    locationName: 'Padianallur (Redhills)',
    lat: 13.23,
    lng: 80.17,
    size: 110000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 38, docks: 10, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-014',
    isActive: true,
    locationName: 'Ponneri (Redhills)',
    lat: 13.21,
    lng: 80.19,
    size: 180000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 42, docks: 18, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-015',
    isActive: true,
    locationName: 'Minjur (Redhills)',
    lat: 13.15,
    lng: 80.05,
    size: 90000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 32, docks: 8, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-016',
    locationName: 'Vengal',
    isActive: true,
    lat: 13.21,
    lng: 79.98,
    size: 250000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 45, docks: 22, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-017',
    locationName: 'Periyapalayam',
    isActive: true,
    lat: 13.31,
    lng: 80.09,
    size: 60000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 28, docks: 4, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-018',
    isActive: true,
    locationName: 'Oragadam',
    lat: 12.84,
    lng: 79.96,
    size: 320000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 50, docks: 30, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-019',
    locationName: 'Sriperumbudur',
    isActive: true,
    lat: 12.97,
    lng: 79.94,
    size: 180000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 15, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-020',
    locationName: 'Mannur',
    isActive: true,
    lat: 13.05,
    lng: 80.01,
    size: 75000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 8, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-021',
    locationName: 'Redhills',
    isActive: true,
    lat: 13.18,
    lng: 80.21,
    size: 150000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 40, docks: 15, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-022',
    locationName: 'Vengal',
    isActive: true,
    lat: 13.22,
    lng: 79.97,
    size: 100000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 35, docks: 10, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-023',
    locationName: 'Sunguvarchatram',
    isActive: true,
    lat: 12.98,
    lng: 79.85,
    size: 200000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 45, docks: 20, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-024',
    locationName: 'Poonamallee',
    isActive: true,
    lat: 13.06,
    lng: 80.11,
    size: 85000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 10, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-025',
    locationName: 'Gurgaon',
    isActive: true,
    lat: 28.45,
    lng: 76.82,
    size: 750000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 50, docks: 60, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-026',
    locationName: 'Pune',
    isActive: true,
    lat: 18.75,
    lng: 73.81,
    size: 400000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 45, docks: 40, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-027',
    locationName: 'Tauranga',
    isActive: true,
    lat: -37.74,
    lng: 176.09,
    size: 200000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 20, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-028',
    locationName: 'Auckland',
    isActive: true,
    lat: -37.00,
    lng: 174.79,
    size: 350000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 50, docks: 30, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-029',
    locationName: 'Polivakkam',
    isActive: true,
    lat: 12.92,
    lng: 80.08,
    size: 150000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 12, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-030',
    locationName: 'Aranvoyal',
    isActive: true,
    lat: 13.11,
    lng: 79.94,
    size: 90000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 35, docks: 8, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-031',
    locationName: 'Koppur',
    isActive: true,
    lat: 13.43,
    lng: 80.12,
    size: 280000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 45, docks: 25, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-032',
    locationName: 'Putlur',
    isActive: true,
    lat: 13.59,
    lng: 80.02,
    size: 500000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 55, docks: 50, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  // New Thiruvallur Data
  createWarehouseEntry({
    id: 'WH-THV-001',
    locationName: 'Polivakkam (Thiruvallur)',
    isActive: true,
    lat: 13.131,
    lng: 79.905,
    size: 110000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 10, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-002',
    locationName: 'Aranvoyal (Thiruvallur)',
    isActive: true,
    lat: 13.133,
    lng: 79.912,
    size: 45000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 28, docks: 4, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-003',
    locationName: 'Koppur (Thiruvallur)',
    isActive: true,
    lat: 13.118,
    lng: 79.938,
    size: 230000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 45, docks: 20, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-004',
    locationName: 'Putlur (Thiruvallur)',
    isActive: true,
    lat: 13.105,
    lng: 79.955,
    size: 95000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 35, docks: 8, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-005',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.109,
    lng: 79.971,
    size: 150000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 42, docks: 14, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-006',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.145,
    lng: 79.921,
    size: 300000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 50, docks: 30, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-007',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.138,
    lng: 79.899,
    size: 30000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 25, docks: 2, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-008',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.151,
    lng: 79.908,
    size: 85000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 38, docks: 8, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-009',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.085,
    lng: 79.885,
    size: 120000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 12, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-010',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.075,
    lng: 79.865,
    size: 180000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 45, docks: 15, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-011',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.160,
    lng: 79.940,
    size: 70000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 6, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-012',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.128,
    lng: 79.880,
    size: 250000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 48, docks: 25, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-013',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.175,
    lng: 79.915,
    size: 90000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 35, docks: 10, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-014',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.030,
    lng: 79.890,
    size: 50000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 5, officeSpace: true, flooringType: 'Insulated' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-015',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.155,
    lng: 79.995,
    size: 160000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 40, docks: 15, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),

    // Delhi NCR
    ...[
        { name: 'Bilaspur', lat: 28.37, lng: 76.85 },
        { name: 'Pataudi Road', lat: 28.36, lng: 76.78 },
        { name: 'Farrukhnagar', lat: 28.45, lng: 76.82 },
        { name: 'Ghaziabad', lat: 28.67, lng: 77.45 },
        { name: 'Noida', lat: 28.53, lng: 77.39 },
        { name: 'Greater Noida', lat: 28.47, lng: 77.50 },
        { name: 'Sonipat', lat: 28.99, lng: 77.02 },
        { name: 'Panipat', lat: 29.39, lng: 76.96 },
        { name: 'Faridabad', lat: 28.41, lng: 77.32 },
    ].flatMap((loc, i) => Array.from({ length: 7 }, (_, j) => createWarehouseEntry({
        id: `WH-NCR-${i * 7 + j + 1}`,
        locationName: loc.name,
        isActive: true,
        lat: loc.lat + (Math.random() - 0.5) * 0.1,
        lng: loc.lng + (Math.random() - 0.5) * 0.1,
        size: Math.floor(Math.random() * 40 + 2) * 5000, // 10k to 200k
        readiness: ['Ready for Occupancy', 'Under Construction', 'Available in 3 months'][j % 3],
        specifications: {
            ceilingHeight: Math.floor(Math.random() * 15 + 25), // 25-40 ft
            docks: Math.floor(Math.random() * 20 + 5), // 5-25
            officeSpace: j % 2 === 0,
            flooringType: ['Standard', 'FM2 Grade'][j % 2],
        },
        imageUrls: ['https://placehold.co/600x400.png'],
    }))),

    // Mumbai MMR
    ...[
        { name: 'Bhiwandi', lat: 19.29, lng: 73.06 },
        { name: 'Panvel', lat: 18.99, lng: 73.12 },
        { name: 'Taloja', lat: 19.09, lng: 73.13 },
        { name: 'Vasai-Virar', lat: 19.47, lng: 72.80 },
    ].flatMap((loc, i) => Array.from({ length: 8 }, (_, j) => createWarehouseEntry({
        id: `WH-MMR-${i * 8 + j + 1}`,
        locationName: loc.name,
        isActive: true,
        lat: loc.lat + (Math.random() - 0.5) * 0.1,
        lng: loc.lng + (Math.random() - 0.5) * 0.1,
        size: Math.floor(Math.random() * 50 + 10) * 10000, // 100k to 600k
        readiness: ['Ready for Occupancy', 'Under Construction', 'Available in 3 months'][j % 3],
        specifications: {
            ceilingHeight: Math.floor(Math.random() * 20 + 30), // 30-50 ft
            docks: Math.floor(Math.random() * 30 + 10), // 10-40
            officeSpace: j % 2 === 0,
            flooringType: ['FM2 Grade', 'Heavy Duty'][j % 2],
        },
        imageUrls: ['https://placehold.co/600x400.png'],
    }))),

    // Pune
    ...[
        { name: 'Chakan-Talegaon', lat: 18.75, lng: 73.81 },
        { name: 'Ranjangaon', lat: 18.75, lng: 74.22 },
        { name: 'Sanaswadi', lat: 18.66, lng: 74.05 },
        { name: 'Wagholi', lat: 18.57, lng: 73.98 },
    ].flatMap((loc, i) => Array.from({ length: 6 }, (_, j) => createWarehouseEntry({
        id: `WH-PUN-${i * 6 + j + 1}`,
        locationName: loc.name,
        isActive: true,
        lat: loc.lat + (Math.random() - 0.5) * 0.1,
        lng: loc.lng + (Math.random() - 0.5) * 0.1,
        size: Math.floor(Math.random() * 30 + 5) * 10000, // 50k to 350k
        readiness: ['Ready for Occupancy', 'Under Construction', 'Available in 3 months'][j % 3],
        specifications: {
            ceilingHeight: Math.floor(Math.random() * 20 + 30), // 30-50 ft
            docks: Math.floor(Math.random() * 25 + 5), // 5-30
            officeSpace: j % 2 === 0,
            flooringType: ['FM2 Grade', 'Standard'][j % 2],
        },
        imageUrls: ['https://placehold.co/600x400.png'],
    }))),
    
    // Bengaluru
    ...[
        { name: 'Hosur-Attibele Road', lat: 12.75, lng: 77.82 },
        { name: 'Dabaspet', lat: 13.23, lng: 77.30 },
        { name: 'Nelamangala', lat: 13.09, lng: 77.40 },
        { name: 'Hoskote', lat: 13.07, lng: 77.79 },
    ].flatMap((loc, i) => Array.from({ length: 8 }, (_, j) => createWarehouseEntry({
        id: `WH-BLR-${i * 8 + j + 1}`,
        locationName: loc.name,
        isActive: true,
        lat: loc.lat + (Math.random() - 0.5) * 0.1,
        lng: loc.lng + (Math.random() - 0.5) * 0.1,
        size: Math.floor(Math.random() * 40 + 10) * 10000, // 100k to 500k
        readiness: ['Ready for Occupancy', 'Under Construction', 'Available in 3 months'][j % 3],
        specifications: {
            ceilingHeight: Math.floor(Math.random() * 20 + 35), // 35-55 ft
            docks: Math.floor(Math.random() * 30 + 10), // 10-40
            officeSpace: j % 2 === 0,
            flooringType: ['FM2 Grade', 'Heavy Duty'][j % 2],
        },
        imageUrls: ['https://placehold.co/600x400.png'],
    }))),
    
    // Chennai
    ...[
        { name: 'Mevalurkuppam', lat: 13.01, lng: 80.01 },
        { name: 'Kuthambakkam', lat: 13.05, lng: 80.05 },
        { name: 'Thirumazhisai', lat: 13.05, lng: 80.03 },
        { name: 'Kunnvakkam', lat: 12.78, lng: 79.94 },
        { name: 'Palur', lat: 12.69, lng: 79.91 },
        { name: 'Maraimalai Nagar', lat: 12.79, lng: 79.98 },
        { name: 'Singaperumal Kovil', lat: 12.82, lng: 79.96 },
        { name: 'Chengalpet', lat: 12.68, lng: 79.98 },
        { name: 'Madhavaram', lat: 13.14, lng: 80.23 },
        { name: 'Karanodai', lat: 13.26, lng: 80.20 },
        { name: 'Thamaraipakkam', lat: 13.20, lng: 80.08 },
        { name: 'Sothupakkam', lat: 12.65, lng: 79.90 },
        { name: 'Vishnuvakkam', lat: 13.17, lng: 79.95 },
    ].flatMap((loc, i) => Array.from({ length: 6 }, (_, j) => createWarehouseEntry({
        id: `WH-CHE-${i * 6 + j + 1}`,
        locationName: loc.name,
        isActive: j % 5 !== 0, // make some inactive
        lat: loc.lat + (Math.random() - 0.5) * 0.05,
        lng: loc.lng + (Math.random() - 0.5) * 0.05,
        size: Math.floor(Math.random() * 25 + 5) * 10000, // 50k to 300k
        readiness: ['Ready for Occupancy', 'Under Construction', 'Available in 3 months'][j % 3],
        specifications: {
            ceilingHeight: Math.floor(Math.random() * 15 + 30), // 30-45 ft
            docks: Math.floor(Math.random() * 20 + 5), // 5-25
            officeSpace: j % 2 === 0,
            flooringType: ['FM2 Grade', 'Standard'][j % 2],
        },
        imageUrls: ['https://placehold.co/600x400.png'],
    }))),
    
    // Hyderabad
    ...[
        { name: 'Patancheru', lat: 17.52, lng: 78.26 },
        { name: 'Medchal', lat: 17.62, lng: 78.48 },
        { name: 'Shamshabad', lat: 17.25, lng: 78.40 },
        { name: 'Kompally', lat: 17.54, lng: 78.50 },
    ].flatMap((loc, i) => Array.from({ length: 7 }, (_, j) => createWarehouseEntry({
        id: `WH-HYD-${i * 7 + j + 1}`,
        locationName: loc.name,
        isActive: true,
        lat: loc.lat + (Math.random() - 0.5) * 0.1,
        lng: loc.lng + (Math.random() - 0.5) * 0.1,
        size: Math.floor(Math.random() * 30 + 10) * 10000, // 100k to 400k
        readiness: ['Ready for Occupancy', 'Under Construction', 'Available in 3 months'][j % 3],
        specifications: {
            ceilingHeight: Math.floor(Math.random() * 15 + 30), // 30-45 ft
            docks: Math.floor(Math.random() * 25 + 5), // 5-30
            officeSpace: j % 2 === 0,
            flooringType: ['FM2 Grade', 'Heavy Duty'][j % 2],
        },
        imageUrls: ['https://placehold.co/600x400.png'],
    }))),
    
    // Kolkata
    ...[
        { name: 'Dankuni', lat: 22.68, lng: 88.31 },
        { name: 'Taratala', lat: 22.50, lng: 88.30 },
        { name: 'Uluberia', lat: 22.47, lng: 88.11 },
    ].flatMap((loc, i) => Array.from({ length: 8 }, (_, j) => createWarehouseEntry({
        id: `WH-KOL-${i * 8 + j + 1}`,
        locationName: loc.name,
        isActive: true,
        lat: loc.lat + (Math.random() - 0.5) * 0.1,
        lng: loc.lng + (Math.random() - 0.5) * 0.1,
        size: Math.floor(Math.random() * 20 + 5) * 10000, // 50k to 250k
        readiness: ['Ready for Occupancy', 'Under Construction', 'Available in 3 months'][j % 3],
        specifications: {
            ceilingHeight: Math.floor(Math.random() * 15 + 25), // 25-40 ft
            docks: Math.floor(Math.random() * 15 + 5), // 5-20
            officeSpace: j % 2 === 0,
            flooringType: ['Standard', 'FM2 Grade'][j % 2],
        },
        imageUrls: ['https://placehold.co/600x400.png'],
    }))),
    
    // Ahmedabad
    ...[
        { name: 'Ahmedabad', lat: 23.02, lng: 72.57 },
        { name: 'Sanand', lat: 22.98, lng: 72.38 },
        { name: 'Changodar', lat: 22.89, lng: 72.46 },
        { name: 'Aslali', lat: 22.93, lng: 72.58 },
    ].flatMap((loc, i) => Array.from({ length: 7 }, (_, j) => createWarehouseEntry({
        id: `WH-AMD-${i * 7 + j + 1}`,
        locationName: loc.name,
        isActive: true,
        lat: loc.lat + (Math.random() - 0.5) * 0.1,
        lng: loc.lng + (Math.random() - 0.5) * 0.1,
        size: Math.floor(Math.random() * 45 + 5) * 10000, // 50k to 500k
        readiness: ['Ready for Occupancy', 'Under Construction', 'Available in 3 months'][j % 3],
        specifications: {
            ceilingHeight: Math.floor(Math.random() * 20 + 30), // 30-50 ft
            docks: Math.floor(Math.random() * 30 + 10), // 10-40
            officeSpace: j % 2 === 0,
            flooringType: ['FM2 Grade', 'Heavy Duty'][j % 2],
        },
        imageUrls: ['https://placehold.co/600x400.png'],
    }))),
    
    // Other Major Cities
    ...[
        { name: 'Nagpur (MIHAN)', lat: 21.09, lng: 79.05 },
        { name: 'Coimbatore', lat: 11.01, lng: 76.95 },
        { name: 'Lucknow', lat: 26.84, lng: 80.94 },
        { name: 'Indore', lat: 22.71, lng: 75.85 },
        { name: 'Jaipur', lat: 26.91, lng: 75.78 },
        { name: 'Visakhapatnam', lat: 17.68, lng: 83.21 },
        { name: 'Guwahati', lat: 26.14, lng: 91.73 },
    ].flatMap((loc, i) => Array.from({ length: 5 }, (_, j) => createWarehouseEntry({
        id: `WH-OTH-${i * 5 + j + 1}`,
        locationName: loc.name,
        isActive: true,
        lat: loc.lat + (Math.random() - 0.5) * 0.1,
        lng: loc.lng + (Math.random() - 0.5) * 0.1,
        size: Math.floor(Math.random() * 20 + 5) * 10000, // 50k to 250k
        readiness: ['Ready for Occupancy', 'Under Construction', 'Available in 3 months'][j % 3],
        specifications: {
            ceilingHeight: Math.floor(Math.random() * 15 + 25), // 25-40 ft
            docks: Math.floor(Math.random() * 15 + 5), // 5-20
            officeSpace: j % 2 === 0,
            flooringType: ['Standard', 'FM2 Grade'][j % 2],
        },
        imageUrls: ['https://placehold.co/600x400.png'],
    })))
];
