
import { type WarehouseSchema } from "./schema";

export const warehouses: WarehouseSchema[] = [
  {
    id: 'WH-001',
    title: 'Modern Logistics Hub in Oragadam',
    isActive: true,
    address: {
        line1: 'Oragadam Industrial Corridor',
        city: 'Oragadam',
        state: 'Tamil Nadu',
        postalCode: '602105',
    },
    generalizedLocation: { lat: 12.83, lng: 79.95 },
    size: 150000,
    readiness: 'Ready for Occupancy',
    specifications: {
        ceilingHeight: 45,
        docks: 20,
        officeSpace: true,
        flooringType: 'FM2 Grade',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  },
  {
    id: 'WH-002',
    title: 'Grade-A Warehouse near Sriperumbudur',
    isActive: true,
    address: {
        line1: 'SIPCOT Industrial Park',
        city: 'Sriperumbudur',
        state: 'Tamil Nadu',
        postalCode: '602105',
    },
    generalizedLocation: { lat: 12.96, lng: 79.95 },
    size: 250000,
    readiness: 'Under Construction',
    specifications: {
        ceilingHeight: 50,
        docks: 30,
        officeSpace: true,
        flooringType: 'Heavy Duty',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  },
  {
    id: 'WH-003',
    title: 'Compact Warehouse in Guindy',
    isActive: false, // This one is inactive
    address: {
        line1: 'Guindy Industrial Estate',
        city: 'Chennai',
        state: 'Tamil Nadu',
        postalCode: '600032',
    },
    generalizedLocation: { lat: 13.0102, lng: 80.2156 },
    size: 50000,
    readiness: 'Ready for Occupancy',
    specifications: {
        ceilingHeight: 25,
        docks: 5,
        officeSpace: true,
        flooringType: 'Standard',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
    ],
  },
  {
    id: 'WH-004',
    title: 'Large Distribution Center in Bhiwandi',
    isActive: true,
    address: {
        line1: 'Mumbai-Nashik Highway',
        city: 'Bhiwandi',
        state: 'Maharashtra',
        postalCode: '421302',
    },
    generalizedLocation: { lat: 19.30, lng: 73.06 },
    size: 500000,
    readiness: 'Ready for Occupancy',
    specifications: {
        ceilingHeight: 40,
        docks: 50,
        officeSpace: true,
        flooringType: 'FM2 Grade',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  },
  {
    id: 'WH-005',
    title: 'E-commerce Fulfillment Center, Hosur',
    isActive: true,
    address: {
        line1: 'Industrial Area',
        city: 'Hosur',
        state: 'Tamil Nadu',
        postalCode: '635109',
    },
    generalizedLocation: { lat: 12.75, lng: 77.82 },
    size: 120000,
    readiness: 'Available in 3 months',
    specifications: {
        ceilingHeight: 40,
        docks: 15,
        officeSpace: false,
        flooringType: 'Standard',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  },
  {
    id: 'WH-006',
    title: 'Thiruvallur Industrial Warehouse',
    isActive: true,
    address: { line1: 'Tiruvallur High Road', city: 'Thiruvallur', state: 'Tamil Nadu', postalCode: '602001' },
    generalizedLocation: { lat: 13.13, lng: 79.91 },
    size: 80000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 35, docks: 8, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-007',
    title: 'Vallam-Vadagal Logistics Park',
    isActive: true,
    address: { line1: 'SIPCOT Vallam-Vadagal', city: 'Vallam', state: 'Tamil Nadu', postalCode: '602105' },
    generalizedLocation: { lat: 12.92, lng: 79.93 },
    size: 300000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 50, docks: 35, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-008',
    title: 'Mannur PEB Warehouse',
    isActive: true,
    address: { line1: 'Mannur Koot Road', city: 'Mannur', state: 'Tamil Nadu', postalCode: '602105' },
    generalizedLocation: { lat: 13.04, lng: 79.99 },
    size: 125000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 12, officeSpace: false, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-009',
    title: 'Mappedu Storage Facility',
    isActive: true,
    address: { line1: 'SH 50B', city: 'Mappedu', state: 'Tamil Nadu', postalCode: '602024' },
    generalizedLocation: { lat: 13.09, lng: 79.95 },
    size: 95000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 30, docks: 10, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-010',
    title: 'Sunguvarchatram Mega Warehouse',
    isActive: true,
    address: { line1: 'Bangalore Highway', city: 'Sunguvarchatram', state: 'Tamil Nadu', postalCode: '602106' },
    generalizedLocation: { lat: 12.97, lng: 79.84 },
    size: 450000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 55, docks: 40, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-011',
    title: 'Walajabad Industrial Unit',
    isActive: true,
    address: { line1: 'Walajabad Industrial Area', city: 'Walajabad', state: 'Tamil Nadu', postalCode: '631605' },
    generalizedLocation: { lat: 12.80, lng: 79.83 },
    size: 75000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 6, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-012',
    title: 'Redhills Logistics Center',
    isActive: true,
    address: { line1: 'GNT Road', city: 'Redhills', state: 'Tamil Nadu', postalCode: '600052' },
    generalizedLocation: { lat: 13.17, lng: 80.20 },
    size: 220000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 40, docks: 25, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-013',
    title: 'Karanodai Supply Hub',
    isActive: true,
    address: { line1: 'Karanodai', city: 'Chennai', state: 'Tamil Nadu', postalCode: '600067' },
    generalizedLocation: { lat: 13.23, lng: 80.17 },
    size: 110000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 38, docks: 10, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-014',
    title: 'Sholavaram Distribution Point',
    isActive: true,
    address: { line1: 'Near Puzhal Lake', city: 'Sholavaram', state: 'Tamil Nadu', postalCode: '600067' },
    generalizedLocation: { lat: 13.21, lng: 80.19 },
    size: 180000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 42, docks: 18, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-015',
    title: 'Thamaraipakkam Warehouse',
    isActive: true,
    address: { line1: 'Thiruvallur High Rd', city: 'Thamaraipakkam', state: 'Tamil Nadu', postalCode: '600052' },
    generalizedLocation: { lat: 13.15, lng: 80.05 },
    size: 90000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 32, docks: 8, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-016',
    title: 'Vengal Gated Community Warehouse',
    isActive: true,
    address: { line1: 'Vengal', city: 'Thiruvallur', state: 'Tamil Nadu', postalCode: '601103' },
    generalizedLocation: { lat: 13.21, lng: 79.98 },
    size: 250000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 45, docks: 22, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-017',
    title: 'Periyapalayam Industrial Shed',
    isActive: true,
    address: { line1: 'State Highway 50A', city: 'Periyapalayam', state: 'Tamil Nadu', postalCode: '601102' },
    generalizedLocation: { lat: 13.31, lng: 80.09 },
    size: 60000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 28, docks: 4, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-018',
    title: 'Oragadam Prime Logistics Park',
    isActive: true,
    address: { line1: 'Vallam-Oragadam Road', city: 'Oragadam', state: 'Tamil Nadu', postalCode: '602105' },
    generalizedLocation: { lat: 12.84, lng: 79.96 },
    size: 320000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 50, docks: 30, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-019',
    title: 'Sriperumbudur Automotive Warehouse',
    isActive: true,
    address: { line1: 'Near Hyundai Factory', city: 'Sriperumbudur', state: 'Tamil Nadu', postalCode: '602105' },
    generalizedLocation: { lat: 12.97, lng: 79.94 },
    size: 180000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 15, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-020',
    title: 'Mannur Compact Storage',
    isActive: true,
    address: { line1: 'Near Saveetha College', city: 'Mannur', state: 'Tamil Nadu', postalCode: '602105' },
    generalizedLocation: { lat: 13.05, lng: 80.01 },
    size: 75000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 8, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-021',
    title: 'Redhills Main Road Facility',
    isActive: true,
    address: { line1: 'Grand Northern Trunk Road', city: 'Redhills', state: 'Tamil Nadu', postalCode: '600052' },
    generalizedLocation: { lat: 13.18, lng: 80.21 },
    size: 150000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 40, docks: 15, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-022',
    title: 'Vengal Industrial Estate Unit',
    isActive: true,
    address: { line1: 'SIDCO Industrial Estate', city: 'Vengal', state: 'Tamil Nadu', postalCode: '601103' },
    generalizedLocation: { lat: 13.22, lng: 79.97 },
    size: 100000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 35, docks: 10, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-023',
    title: 'Sunguvarchatram Industrial Park',
    isActive: true,
    address: { line1: 'Mahindra World City Road', city: 'Sunguvarchatram', state: 'Tamil Nadu', postalCode: '602106' },
    generalizedLocation: { lat: 12.98, lng: 79.85 },
    size: 200000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 45, docks: 20, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-024',
    title: 'Poonamallee Last Mile Hub',
    isActive: true,
    address: { line1: 'Poonamallee High Road', city: 'Poonamallee', state: 'Tamil Nadu', postalCode: '600056' },
    generalizedLocation: { lat: 13.06, lng: 80.11 },
    size: 85000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 10, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-025',
    title: 'Faruknagar Logistics Park, Gurgaon',
    isActive: true,
    address: { line1: 'Near KMP Expressway', city: 'Faruknagar', state: 'Haryana', postalCode: '122506' },
    generalizedLocation: { lat: 28.45, lng: 76.82 },
    size: 750000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 50, docks: 60, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-026',
    title: 'Chakan MIDC Warehouse, Pune',
    isActive: true,
    address: { line1: 'Chakan Industrial Area', city: 'Pune', state: 'Maharashtra', postalCode: '410501' },
    generalizedLocation: { lat: 18.75, lng: 73.81 },
    size: 400000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 45, docks: 40, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-027',
    title: 'Tauranga Port Logistics, NZ',
    isActive: true,
    address: { line1: 'Tauriko Business Estate', city: 'Tauranga', state: 'Bay of Plenty', postalCode: '3110' },
    generalizedLocation: { lat: -37.74, lng: 176.09 },
    size: 200000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 20, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-028',
    title: 'Auckland Airport Cargo Hub, NZ',
    isActive: true,
    address: { line1: 'Airport Oaks', city: 'Auckland', state: 'Auckland', postalCode: '2022' },
    generalizedLocation: { lat: -37.00, lng: 174.79 },
    size: 350000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 50, docks: 30, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-029',
    title: 'Outer Ring Road Warehouse, Chennai',
    isActive: true,
    address: { line1: 'Near Vandalur', city: 'Chennai', state: 'Tamil Nadu', postalCode: '600048' },
    generalizedLocation: { lat: 12.92, lng: 80.08 },
    size: 150000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 12, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-030',
    title: 'Polivakkam Industrial Unit',
    isActive: true,
    address: { line1: 'Tiruvallur Road', city: 'Polivakkam', state: 'Tamil Nadu', postalCode: '602002' },
    generalizedLocation: { lat: 13.11, lng: 79.94 },
    size: 90000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 35, docks: 8, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-031',
    title: 'Gummidipoondi SIPCOT Warehouse',
    isActive: true,
    address: { line1: 'SIPCOT Industrial Complex', city: 'Gummidipoondi', state: 'Tamil Nadu', postalCode: '601201' },
    generalizedLocation: { lat: 13.43, lng: 80.12 },
    size: 280000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 45, docks: 25, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'WH-032',
    title: 'Tada, Andhra Pradesh Border Facility',
    isActive: true,
    address: { line1: 'Sri City', city: 'Tada', state: 'Andhra Pradesh', postalCode: '524401' },
    generalizedLocation: { lat: 13.59, lng: 80.02 },
    size: 500000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 55, docks: 50, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }
];
