
import { type WarehouseSchema } from "./schema";

// This is a helper function to satisfy the transformed schema structure
const createWarehouseEntry = (entry: Omit<WarehouseSchema, 'latLng' | 'generalizedLocation'> & {
    lat: number;
    lng: number;
}): WarehouseSchema => {
    return {
        ...entry,
        latLng: `${entry.lat}, ${entry.lng}`,
        generalizedLocation: {
            lat: entry.lat,
            lng: entry.lng,
        }
    };
};


export const warehouses: WarehouseSchema[] = [
  createWarehouseEntry({
    id: 'WH-001',
    locationName: 'Oragadam',
    isActive: true,
    lat: 12.83,
    lng: 79.95,
    size: 150000,
    readiness: 'Ready for Occupancy',
    specifications: {
        ceilingHeight: 45,
        docks: 20,
        officeSpace: true,
        flooringType: 'FM2 Grade',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  }),
  createWarehouseEntry({
    id: 'WH-002',
    locationName: 'Sriperumbudur',
    isActive: true,
    lat: 12.96,
    lng: 79.95,
    size: 250000,
    readiness: 'Under Construction',
    specifications: {
        ceilingHeight: 50,
        docks: 30,
        officeSpace: true,
        flooringType: 'Heavy Duty',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  }),
  createWarehouseEntry({
    id: 'WH-003',
    locationName: 'Guindy',
    isActive: false, // This one is inactive
    lat: 13.0102,
    lng: 80.2156,
    size: 50000,
    readiness: 'Ready for Occupancy',
    specifications: {
        ceilingHeight: 25,
        docks: 5,
        officeSpace: true,
        flooringType: 'Standard',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
    ],
  }),
  createWarehouseEntry({
    id: 'WH-004',
    locationName: 'Bhiwandi',
    isActive: true,
    lat: 19.30,
    lng: 73.06,
    size: 500000,
    readiness: 'Ready for Occupancy',
    specifications: {
        ceilingHeight: 40,
        docks: 50,
        officeSpace: true,
        flooringType: 'FM2 Grade',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  }),
  createWarehouseEntry({
    id: 'WH-005',
    locationName: 'Hosur',
    isActive: true,
    lat: 12.75,
    lng: 77.82,
    size: 120000,
    readiness: 'Available in 3 months',
    specifications: {
        ceilingHeight: 40,
        docks: 15,
        officeSpace: false,
        flooringType: 'Standard',
    },
    imageUrls: [
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
    ],
  }),
  createWarehouseEntry({
    id: 'WH-006',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.13,
    lng: 79.91,
    size: 80000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 35, docks: 8, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-007',
    locationName: 'Vallam-Vadagal',
    isActive: true,
    lat: 12.92,
    lng: 79.93,
    size: 300000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 50, docks: 35, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-008',
    locationName: 'Mannur',
    isActive: true,
    lat: 13.04,
    lng: 79.99,
    size: 125000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 12, officeSpace: false, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-009',
    locationName: 'Mappedu',
    isActive: true,
    lat: 13.09,
    lng: 79.95,
    size: 95000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 30, docks: 10, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-010',
    locationName: 'Sunguvarchatram',
    isActive: true,
    lat: 12.97,
    lng: 79.84,
    size: 450000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 55, docks: 40, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-011',
    locationName: 'Walajabad',
    isActive: true,
    lat: 12.80,
    lng: 79.83,
    size: 75000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 6, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-012',
    locationName: 'Redhills',
    isActive: true,
    lat: 13.17,
    lng: 80.20,
    size: 220000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 40, docks: 25, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-013',
    isActive: true,
    locationName: 'Padianallur (Redhills)',
    lat: 13.23,
    lng: 80.17,
    size: 110000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 38, docks: 10, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-014',
    isActive: true,
    locationName: 'Ponneri (Redhills)',
    lat: 13.21,
    lng: 80.19,
    size: 180000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 42, docks: 18, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-015',
    isActive: true,
    locationName: 'Minjur (Redhills)',
    lat: 13.15,
    lng: 80.05,
    size: 90000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 32, docks: 8, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-016',
    locationName: 'Vengal',
    isActive: true,
    lat: 13.21,
    lng: 79.98,
    size: 250000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 45, docks: 22, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-017',
    locationName: 'Periyapalayam',
    isActive: true,
    lat: 13.31,
    lng: 80.09,
    size: 60000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 28, docks: 4, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-018',
    isActive: true,
    locationName: 'Oragadam',
    lat: 12.84,
    lng: 79.96,
    size: 320000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 50, docks: 30, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-019',
    locationName: 'Sriperumbudur',
    isActive: true,
    lat: 12.97,
    lng: 79.94,
    size: 180000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 15, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-020',
    locationName: 'Mannur',
    isActive: true,
    lat: 13.05,
    lng: 80.01,
    size: 75000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 8, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-021',
    locationName: 'Redhills',
    isActive: true,
    lat: 13.18,
    lng: 80.21,
    size: 150000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 40, docks: 15, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-022',
    locationName: 'Vengal',
    isActive: true,
    lat: 13.22,
    lng: 79.97,
    size: 100000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 35, docks: 10, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-023',
    locationName: 'Sunguvarchatram',
    isActive: true,
    lat: 12.98,
    lng: 79.85,
    size: 200000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 45, docks: 20, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-024',
    locationName: 'Poonamallee',
    isActive: true,
    lat: 13.06,
    lng: 80.11,
    size: 85000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 10, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-025',
    locationName: 'Gurgaon',
    isActive: true,
    lat: 28.45,
    lng: 76.82,
    size: 750000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 50, docks: 60, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-026',
    locationName: 'Pune',
    isActive: true,
    lat: 18.75,
    lng: 73.81,
    size: 400000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 45, docks: 40, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-027',
    locationName: 'Tauranga',
    isActive: true,
    lat: -37.74,
    lng: 176.09,
    size: 200000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 20, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-028',
    locationName: 'Auckland',
    isActive: true,
    lat: -37.00,
    lng: 174.79,
    size: 350000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 50, docks: 30, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-029',
    locationName: 'Polivakkam',
    isActive: true,
    lat: 12.92,
    lng: 80.08,
    size: 150000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 12, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-030',
    locationName: 'Aranvoyal',
    isActive: true,
    lat: 13.11,
    lng: 79.94,
    size: 90000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 35, docks: 8, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-031',
    locationName: 'Koppur',
    isActive: true,
    lat: 13.43,
    lng: 80.12,
    size: 280000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 45, docks: 25, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-032',
    locationName: 'Putlur',
    isActive: true,
    lat: 13.59,
    lng: 80.02,
    size: 500000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 55, docks: 50, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  // New Thiruvallur Data
  createWarehouseEntry({
    id: 'WH-THV-001',
    locationName: 'Polivakkam (Thiruvallur)',
    isActive: true,
    lat: 13.131,
    lng: 79.905,
    size: 110000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 10, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-002',
    locationName: 'Aranvoyal (Thiruvallur)',
    isActive: true,
    lat: 13.133,
    lng: 79.912,
    size: 45000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 28, docks: 4, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-003',
    locationName: 'Koppur (Thiruvallur)',
    isActive: true,
    lat: 13.118,
    lng: 79.938,
    size: 230000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 45, docks: 20, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-004',
    locationName: 'Putlur (Thiruvallur)',
    isActive: true,
    lat: 13.105,
    lng: 79.955,
    size: 95000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 35, docks: 8, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-005',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.109,
    lng: 79.971,
    size: 150000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 42, docks: 14, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-006',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.145,
    lng: 79.921,
    size: 300000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 50, docks: 30, officeSpace: true, flooringType: 'Superflat' },
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-007',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.138,
    lng: 79.899,
    size: 30000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 25, docks: 2, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-008',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.151,
    lng: 79.908,
    size: 85000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 38, docks: 8, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-009',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.085,
    lng: 79.885,
    size: 120000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 40, docks: 12, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-010',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.075,
    lng: 79.865,
    size: 180000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 45, docks: 15, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-011',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.160,
    lng: 79.940,
    size: 70000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 6, officeSpace: true, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-012',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.128,
    lng: 79.880,
    size: 250000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 48, docks: 25, officeSpace: true, flooringType: 'Heavy Duty' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-013',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.175,
    lng: 79.915,
    size: 90000,
    readiness: 'Under Construction',
    specifications: { ceilingHeight: 35, docks: 10, officeSpace: false, flooringType: 'Standard' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-014',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.030,
    lng: 79.890,
    size: 50000,
    readiness: 'Ready for Occupancy',
    specifications: { ceilingHeight: 30, docks: 5, officeSpace: true, flooringType: 'Insulated' },
    imageUrls: ['https://placehold.co/600x400.png'],
  }),
  createWarehouseEntry({
    id: 'WH-THV-015',
    locationName: 'Thiruvallur',
    isActive: true,
    lat: 13.155,
    lng: 79.995,
    size: 160000,
    readiness: 'Available in 3 months',
    specifications: { ceilingHeight: 40, docks: 15, officeSpace: true, flooringType: 'FM2 Grade' },
    imageUrls: ['https://placehold.co/600x400.png'],
  })
];
